#include "web_admin.h"
const char lab_web_admin[] = R"HTML(
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#071426"><title>ESP32 LAB • Privé</title><style>
:root{--bg:#06111f;--p:#0a1d32;--p2:#0e2a46;--line:#1a3e60;--txt:#eaf6ff;--mut:#91acc5;--cyan:#37dcff;--ok:#2be8a5;--warn:#ffc34e;--bad:#ff6680;--vio:#bd79ff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(900px 420px at 50% -180px,#164b7a66,transparent),var(--bg);color:var(--txt);font:14px system-ui,-apple-system,Segoe UI,sans-serif}.wrap{max-width:1000px;margin:auto;padding:14px}.bar,.card{background:linear-gradient(180deg,#0d2440ee,#08192b);border:1px solid var(--line);border-radius:20px;box-shadow:0 18px 50px #0005}.bar{padding:14px 16px;position:sticky;top:10px;z-index:5;display:flex;justify-content:space-between}.card{padding:16px;margin-top:12px}.mut{color:var(--mut)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.btn{border:1px solid #24557d;border-radius:13px;padding:11px 13px;background:#10304f;color:var(--txt);font-weight:800;cursor:pointer}.btn:active{transform:scale(.98);filter:brightness(1.15)}input,select{width:100%;padding:10px;border-radius:11px;background:#071725;color:var(--txt);border:1px solid var(--line)}label{display:block;color:var(--mut);font-size:11px;margin:8px 0 5px}.pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:6px 9px;font-size:11px;font-weight:800}.ok{color:var(--ok)}.warn{color:var(--warn)}.bad{color:var(--bad)}pre{white-space:pre-wrap;background:#040d17;border:1px solid #17324a;border-radius:12px;padding:10px;max-height:360px;overflow:auto}.danger{color:#ffd0d8;border-color:#79344a;background:#2a1420}@media(max-width:700px){.grid,.row{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><div class="bar"><div><b>ESP32 LAB</b><div class="mut">Panneau de contrôle privé</div></div><div class="pill ok">SESSION PRIVÉE</div></div>
<div class="card"><b>Configuration</b><div class="grid"><div><label>Nom du réseau AP</label><input id="apssid"></div><div><label>Mot de passe AP</label><input id="appass" type="password"></div><div><label>Wi-Fi Internet (SSID)</label><input id="stassid"></div><div><label>Wi-Fi Internet (mot de passe)</label><input id="stapass" type="password"></div><div><label>Numéro WhatsApp</label><input id="waphone"></div><div><label>API CallMeBot</label><input id="waapi" type="password"></div><div><label>Endpoint IA compatible OpenAI</label><input id="aiep" placeholder="https://.../v1/chat/completions"></div><div><label>Clé IA</label><input id="aikey" type="password"></div><div><label>Modèle IA</label><input id="aimodel"></div><div><label>Manifest OTA HTTPS</label><input id="manifest"></div><div><label>GPIO RGB</label><select id="rgb"><option value="48">48 • DevKitC-1 v1.0</option><option value="38">38 • DevKitC-1 v1.1</option></select></div><div><label>Recherche HTTPS</label><input id="search"></div></div><div style="margin-top:12px"><label><input id="auto" type="checkbox" style="width:auto"> Activer vérification OTA automatique</label></div><div style="margin-top:12px"><button class="btn" onclick="save()">Enregistrer + redémarrer</button> <button class="btn" onclick="testWA()">Envoyer « coucou » WhatsApp</button></div></div>
<div class="card"><b>Maintenance</b><div class="row"><button class="btn" onclick="updateCheck()">Vérifier une release</button><button class="btn" onclick="checkUsb()">État USB/AVR</button></div><pre id="out">chargement...</pre></div>
<div class="card"><b>Session</b><button class="btn danger" onclick="location.reload()">Recharger / fermer la session</button></div>
<script>
const $=id=>document.getElementById(id);async function api(u,o={}){const r=await fetch(u,o);const t=await r.text();try{return JSON.parse(t)}catch{return{status:r.status,raw:t}}}
async function load(){const c=await api('/api/admin/config');if(c.ok){['apssid','stassid','aiep','aimodel','manifest','search'].forEach(id=>$(id).value=c[id]||'');$('rgb').value=String(c.rgb_gpio||38);$('auto').checked=!!c.auto_updates;}else $('out').textContent=JSON.stringify(c,null,2)}
async function save(){const d={ap_ssid:$('apssid').value,ap_pass:$('appass').value,sta_ssid:$('stassid').value,sta_pass:$('stapass').value,whatsapp_phone:$('waphone').value,whatsapp_api:$('waapi').value,ai_endpoint:$('aiep').value,ai_key:$('aikey').value,ai_model:$('aimodel').value,search_endpoint:$('search').value,update_manifest:$('manifest').value,rgb_gpio:+$('rgb').value,auto_updates:$('auto').checked};const r=await api('/api/admin/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});$('out').textContent=JSON.stringify(r,null,2)}
async function testWA(){const r=await api('/api/notify/test',{method:'POST'});$('out').textContent=JSON.stringify(r,null,2)}async function updateCheck(){const r=await api('/api/update/check',{method:'POST'});$('out').textContent=JSON.stringify(r,null,2)}function checkUsb(){$('out').textContent='Le statut USB/AVR complet est visible depuis le dashboard et les journaux système.'}load();
</script></div></body></html>)HTML";
const unsigned lab_web_admin_len = sizeof(lab_web_admin) - 1;
